from __future__ import annotations

from typing import Any

from botocore.exceptions import ClientError
from cryptography.exceptions import InvalidTag
from pydantic import BaseModel, ConfigDict

from aws_util._client import get_client
from aws_util.exceptions import wrap_aws_error

__all__ = [
    "CancelKeyDeletionResult",
    "CreateCustomKeyStoreResult",
    "CreateGrantResult",
    "CreateKeyResult",
    "DataKey",
    "DeleteImportedKeyMaterialResult",
    "DeriveSharedSecretResult",
    "DescribeCustomKeyStoresResult",
    "DescribeKeyResult",
    "EncryptResult",
    "GenerateDataKeyPairResult",
    "GenerateDataKeyPairWithoutPlaintextResult",
    "GenerateDataKeyWithoutPlaintextResult",
    "GenerateMacResult",
    "GenerateRandomResult",
    "GetKeyPolicyResult",
    "GetKeyRotationStatusResult",
    "GetParametersForImportResult",
    "GetPublicKeyResult",
    "ImportKeyMaterialResult",
    "ListAliasesResult",
    "ListGrantsResult",
    "ListKeyPoliciesResult",
    "ListKeyRotationsResult",
    "ListKeysResult",
    "ListResourceTagsResult",
    "ListRetirableGrantsResult",
    "ReplicateKeyResult",
    "RotateKeyOnDemandResult",
    "ScheduleKeyDeletionResult",
    "SignResult",
    "VerifyMacResult",
    "VerifyResult",
    "cancel_key_deletion",
    "connect_custom_key_store",
    "create_alias",
    "create_custom_key_store",
    "create_grant",
    "create_key",
    "decrypt",
    "decrypt_data_key",
    "delete_alias",
    "delete_custom_key_store",
    "delete_imported_key_material",
    "derive_shared_secret",
    "describe_custom_key_stores",
    "describe_key",
    "disable_key",
    "disable_key_rotation",
    "disconnect_custom_key_store",
    "enable_key",
    "enable_key_rotation",
    "encrypt",
    "envelope_decrypt",
    "envelope_encrypt",
    "generate_data_key",
    "generate_data_key_pair",
    "generate_data_key_pair_without_plaintext",
    "generate_data_key_without_plaintext",
    "generate_mac",
    "generate_random",
    "get_key_policy",
    "get_key_rotation_status",
    "get_parameters_for_import",
    "get_public_key",
    "import_key_material",
    "list_aliases",
    "list_grants",
    "list_key_policies",
    "list_key_rotations",
    "list_keys",
    "list_resource_tags",
    "list_retirable_grants",
    "put_key_policy",
    "re_encrypt",
    "replicate_key",
    "retire_grant",
    "revoke_grant",
    "rotate_key_on_demand",
    "schedule_key_deletion",
    "sign",
    "tag_resource",
    "untag_resource",
    "update_alias",
    "update_custom_key_store",
    "update_key_description",
    "update_primary_region",
    "verify",
    "verify_mac",
]

# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class EncryptResult(BaseModel):
    """Result of a KMS ``Encrypt`` call."""

    model_config = ConfigDict(frozen=True)

    ciphertext_blob: bytes
    key_id: str
    encryption_algorithm: str


class DataKey(BaseModel):
    """A data key generated by KMS for envelope encryption."""

    model_config = ConfigDict(frozen=True)

    plaintext: bytes
    """Raw plaintext data key — use immediately and discard from memory."""

    ciphertext_blob: bytes
    """Encrypted form of the data key — safe to store alongside ciphertext."""

    key_id: str


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def encrypt(
    key_id: str,
    plaintext: str | bytes,
    encryption_algorithm: str = "SYMMETRIC_DEFAULT",
    region_name: str | None = None,
) -> EncryptResult:
    """Encrypt data using a KMS key.

    Args:
        key_id: KMS key ID, alias (``"alias/my-key"``), or ARN.
        plaintext: Data to encrypt.  Strings are UTF-8 encoded automatically.
        encryption_algorithm: KMS encryption algorithm.  Use
            ``"SYMMETRIC_DEFAULT"`` (default) for symmetric keys.
        region_name: AWS region override.

    Returns:
        An :class:`EncryptResult` containing the ciphertext blob.

    Raises:
        RuntimeError: If encryption fails.
    """
    client = get_client("kms", region_name)
    raw = plaintext.encode("utf-8") if isinstance(plaintext, str) else plaintext
    try:
        resp = client.encrypt(
            KeyId=key_id,
            Plaintext=raw,
            EncryptionAlgorithm=encryption_algorithm,
        )
    except ClientError as exc:
        raise wrap_aws_error(exc, f"Failed to encrypt with KMS key {key_id!r}") from exc
    return EncryptResult(
        ciphertext_blob=resp["CiphertextBlob"],
        key_id=resp["KeyId"],
        encryption_algorithm=resp.get("EncryptionAlgorithm", encryption_algorithm),
    )


def decrypt(
    ciphertext_blob: bytes,
    key_id: str | None = None,
    encryption_algorithm: str = "SYMMETRIC_DEFAULT",
    region_name: str | None = None,
) -> bytes:
    """Decrypt a ciphertext blob using KMS.

    Args:
        ciphertext_blob: The encrypted bytes returned by :func:`encrypt`.
        key_id: KMS key ID, alias, or ARN.  Required for asymmetric keys;
            optional for symmetric keys (KMS infers the key from the
            ciphertext).
        encryption_algorithm: Algorithm that was used to encrypt the data.
        region_name: AWS region override.

    Returns:
        The original plaintext as bytes.

    Raises:
        RuntimeError: If decryption fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict = {
        "CiphertextBlob": ciphertext_blob,
        "EncryptionAlgorithm": encryption_algorithm,
    }
    if key_id is not None:
        kwargs["KeyId"] = key_id
    try:
        resp = client.decrypt(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "KMS decryption failed") from exc
    return resp["Plaintext"]


def generate_data_key(
    key_id: str,
    key_spec: str = "AES_256",
    region_name: str | None = None,
) -> DataKey:
    """Generate a data key for envelope encryption.

    Use the returned plaintext key to encrypt your data locally, then store
    the encrypted ``ciphertext_blob`` alongside the data.  Discard the
    plaintext key from memory after use.

    Args:
        key_id: KMS CMK ID, alias, or ARN used to protect the data key.
        key_spec: ``"AES_256"`` (default) or ``"AES_128"``.
        region_name: AWS region override.

    Returns:
        A :class:`DataKey` with both the plaintext and encrypted key material.

    Raises:
        RuntimeError: If key generation fails.
    """
    client = get_client("kms", region_name)
    try:
        resp = client.generate_data_key(KeyId=key_id, KeySpec=key_spec)
    except ClientError as exc:
        raise wrap_aws_error(exc, f"Failed to generate data key with KMS key {key_id!r}") from exc
    return DataKey(
        plaintext=resp["Plaintext"],
        ciphertext_blob=resp["CiphertextBlob"],
        key_id=resp["KeyId"],
    )


# ---------------------------------------------------------------------------
# Complex utilities
# ---------------------------------------------------------------------------


def envelope_encrypt(
    key_id: str,
    plaintext: bytes | str,
    region_name: str | None = None,
) -> dict[str, bytes]:
    """Encrypt data using the envelope encryption pattern.

    Generates a one-time AES-256 data key via KMS, encrypts *plaintext*
    locally with AES-GCM, and returns both the ciphertext and the encrypted
    data key.  The plaintext data key never leaves memory after this call.

    Args:
        key_id: KMS CMK ID, alias (``"alias/my-key"``), or ARN.
        plaintext: Data to encrypt.  Strings are UTF-8 encoded.
        region_name: AWS region override.

    Returns:
        A dict with keys:
        - ``"ciphertext"`` — AES-GCM ciphertext bytes (nonce prepended)
        - ``"encrypted_data_key"`` — KMS-encrypted data key bytes (store
          alongside ciphertext; pass to :func:`envelope_decrypt`)

    Raises:
        RuntimeError: If KMS key generation fails.
    """
    import os

    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    data_key = generate_data_key(key_id, region_name=region_name)
    raw = plaintext.encode("utf-8") if isinstance(plaintext, str) else plaintext

    nonce = os.urandom(12)
    aesgcm = AESGCM(data_key.plaintext)
    ciphertext = nonce + aesgcm.encrypt(nonce, raw, None)

    # Note: `del` removes the name binding but does NOT zero the underlying
    # memory.  True key material erasure is not possible in CPython without
    # ctypes.  The plaintext key remains in the DataKey model until garbage
    # collected.
    del aesgcm

    return {
        "ciphertext": ciphertext,
        "encrypted_data_key": data_key.ciphertext_blob,
    }


def envelope_decrypt(
    ciphertext: bytes,
    encrypted_data_key: bytes,
    region_name: str | None = None,
) -> bytes:
    """Decrypt data produced by :func:`envelope_encrypt`.

    Uses KMS to recover the data key, then decrypts the ciphertext locally
    with AES-GCM.

    Args:
        ciphertext: The ``"ciphertext"`` value returned by
            :func:`envelope_encrypt`.
        encrypted_data_key: The ``"encrypted_data_key"`` value returned by
            :func:`envelope_encrypt`.
        region_name: AWS region override.

    Returns:
        The original plaintext as bytes.

    Raises:
        RuntimeError: If KMS decryption or AES-GCM authentication fails.
    """
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    plaintext_key = decrypt_data_key(encrypted_data_key, region_name=region_name)
    nonce = ciphertext[:12]
    data = ciphertext[12:]
    aesgcm = AESGCM(plaintext_key)
    try:
        return aesgcm.decrypt(nonce, data, None)
    except (InvalidTag, ValueError) as exc:
        raise wrap_aws_error(exc, "envelope_decrypt failed") from exc


def re_encrypt(
    ciphertext_blob: bytes,
    destination_key_id: str,
    source_key_id: str | None = None,
    region_name: str | None = None,
) -> EncryptResult:
    """Re-encrypt a ciphertext under a different KMS key without exposing the plaintext.

    Useful for key rotation: move data encrypted under an old key to a new key
    without decrypting it locally.  KMS performs the decrypt/re-encrypt
    operation entirely within the service boundary.

    Args:
        ciphertext_blob: Ciphertext bytes produced by :func:`encrypt`.
        destination_key_id: KMS key ID, alias, or ARN of the new key.
        source_key_id: KMS key ID, alias, or ARN of the current key.
            Required for asymmetric source keys; optional for symmetric keys.
        region_name: AWS region override.

    Returns:
        An :class:`EncryptResult` containing the re-encrypted ciphertext.

    Raises:
        RuntimeError: If re-encryption fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict = {
        "CiphertextBlob": ciphertext_blob,
        "DestinationKeyId": destination_key_id,
    }
    if source_key_id is not None:
        kwargs["SourceKeyId"] = source_key_id
    try:
        resp = client.re_encrypt(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, f"Failed to re-encrypt to key {destination_key_id!r}") from exc
    return EncryptResult(
        ciphertext_blob=resp["CiphertextBlob"],
        key_id=resp["KeyId"],
        encryption_algorithm=resp.get("DestinationEncryptionAlgorithm", "SYMMETRIC_DEFAULT"),
    )


def decrypt_data_key(
    ciphertext_blob: bytes,
    region_name: str | None = None,
) -> bytes:
    """Decrypt an encrypted data key generated by :func:`generate_data_key`.

    Convenience alias for the envelope encryption pattern — semantically
    distinct from general-purpose :func:`decrypt`.

    Args:
        ciphertext_blob: The ``ciphertext_blob`` field from a
            :class:`DataKey`.
        region_name: AWS region override.

    Returns:
        The plaintext data key as bytes.
    """
    # Convenience alias for the envelope encryption pattern — semantically
    # distinct from general-purpose decrypt.
    return decrypt(ciphertext_blob=ciphertext_blob, region_name=region_name)


class CancelKeyDeletionResult(BaseModel):
    """Result of cancel_key_deletion."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None


class CreateCustomKeyStoreResult(BaseModel):
    """Result of create_custom_key_store."""

    model_config = ConfigDict(frozen=True)

    custom_key_store_id: str | None = None


class CreateGrantResult(BaseModel):
    """Result of create_grant."""

    model_config = ConfigDict(frozen=True)

    grant_token: str | None = None
    grant_id: str | None = None


class CreateKeyResult(BaseModel):
    """Result of create_key."""

    model_config = ConfigDict(frozen=True)

    key_metadata: dict[str, Any] | None = None


class DeleteImportedKeyMaterialResult(BaseModel):
    """Result of delete_imported_key_material."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    key_material_id: str | None = None


class DeriveSharedSecretResult(BaseModel):
    """Result of derive_shared_secret."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    shared_secret: bytes | None = None
    ciphertext_for_recipient: bytes | None = None
    key_agreement_algorithm: str | None = None
    key_origin: str | None = None


class DescribeCustomKeyStoresResult(BaseModel):
    """Result of describe_custom_key_stores."""

    model_config = ConfigDict(frozen=True)

    custom_key_stores: list[dict[str, Any]] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class DescribeKeyResult(BaseModel):
    """Result of describe_key."""

    model_config = ConfigDict(frozen=True)

    key_metadata: dict[str, Any] | None = None


class GenerateDataKeyPairResult(BaseModel):
    """Result of generate_data_key_pair."""

    model_config = ConfigDict(frozen=True)

    private_key_ciphertext_blob: bytes | None = None
    private_key_plaintext: bytes | None = None
    public_key: bytes | None = None
    key_id: str | None = None
    key_pair_spec: str | None = None
    ciphertext_for_recipient: bytes | None = None
    key_material_id: str | None = None


class GenerateDataKeyPairWithoutPlaintextResult(BaseModel):
    """Result of generate_data_key_pair_without_plaintext."""

    model_config = ConfigDict(frozen=True)

    private_key_ciphertext_blob: bytes | None = None
    public_key: bytes | None = None
    key_id: str | None = None
    key_pair_spec: str | None = None
    key_material_id: str | None = None


class GenerateDataKeyWithoutPlaintextResult(BaseModel):
    """Result of generate_data_key_without_plaintext."""

    model_config = ConfigDict(frozen=True)

    ciphertext_blob: bytes | None = None
    key_id: str | None = None
    key_material_id: str | None = None


class GenerateMacResult(BaseModel):
    """Result of generate_mac."""

    model_config = ConfigDict(frozen=True)

    mac: bytes | None = None
    mac_algorithm: str | None = None
    key_id: str | None = None


class GenerateRandomResult(BaseModel):
    """Result of generate_random."""

    model_config = ConfigDict(frozen=True)

    plaintext: bytes | None = None
    ciphertext_for_recipient: bytes | None = None


class GetKeyPolicyResult(BaseModel):
    """Result of get_key_policy."""

    model_config = ConfigDict(frozen=True)

    policy: str | None = None
    policy_name: str | None = None


class GetKeyRotationStatusResult(BaseModel):
    """Result of get_key_rotation_status."""

    model_config = ConfigDict(frozen=True)

    key_rotation_enabled: bool | None = None
    key_id: str | None = None
    rotation_period_in_days: int | None = None
    next_rotation_date: str | None = None
    on_demand_rotation_start_date: str | None = None


class GetParametersForImportResult(BaseModel):
    """Result of get_parameters_for_import."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    import_token: bytes | None = None
    public_key: bytes | None = None
    parameters_valid_to: str | None = None


class GetPublicKeyResult(BaseModel):
    """Result of get_public_key."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    public_key: bytes | None = None
    customer_master_key_spec: str | None = None
    key_spec: str | None = None
    key_usage: str | None = None
    encryption_algorithms: list[str] | None = None
    signing_algorithms: list[str] | None = None
    key_agreement_algorithms: list[str] | None = None


class ImportKeyMaterialResult(BaseModel):
    """Result of import_key_material."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    key_material_id: str | None = None


class ListAliasesResult(BaseModel):
    """Result of list_aliases."""

    model_config = ConfigDict(frozen=True)

    aliases: list[dict[str, Any]] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class ListGrantsResult(BaseModel):
    """Result of list_grants."""

    model_config = ConfigDict(frozen=True)

    grants: list[dict[str, Any]] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class ListKeyPoliciesResult(BaseModel):
    """Result of list_key_policies."""

    model_config = ConfigDict(frozen=True)

    policy_names: list[str] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class ListKeyRotationsResult(BaseModel):
    """Result of list_key_rotations."""

    model_config = ConfigDict(frozen=True)

    rotations: list[dict[str, Any]] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class ListKeysResult(BaseModel):
    """Result of list_keys."""

    model_config = ConfigDict(frozen=True)

    keys: list[dict[str, Any]] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class ListResourceTagsResult(BaseModel):
    """Result of list_resource_tags."""

    model_config = ConfigDict(frozen=True)

    tags: list[dict[str, Any]] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class ListRetirableGrantsResult(BaseModel):
    """Result of list_retirable_grants."""

    model_config = ConfigDict(frozen=True)

    grants: list[dict[str, Any]] | None = None
    next_marker: str | None = None
    truncated: bool | None = None


class ReplicateKeyResult(BaseModel):
    """Result of replicate_key."""

    model_config = ConfigDict(frozen=True)

    replica_key_metadata: dict[str, Any] | None = None
    replica_policy: str | None = None
    replica_tags: list[dict[str, Any]] | None = None


class RotateKeyOnDemandResult(BaseModel):
    """Result of rotate_key_on_demand."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None


class ScheduleKeyDeletionResult(BaseModel):
    """Result of schedule_key_deletion."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    deletion_date: str | None = None
    key_state: str | None = None
    pending_window_in_days: int | None = None


class SignResult(BaseModel):
    """Result of sign."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    signature: bytes | None = None
    signing_algorithm: str | None = None


class VerifyResult(BaseModel):
    """Result of verify."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    signature_valid: bool | None = None
    signing_algorithm: str | None = None


class VerifyMacResult(BaseModel):
    """Result of verify_mac."""

    model_config = ConfigDict(frozen=True)

    key_id: str | None = None
    mac_valid: bool | None = None
    mac_algorithm: str | None = None


def cancel_key_deletion(
    key_id: str,
    region_name: str | None = None,
) -> CancelKeyDeletionResult:
    """Cancel key deletion.

    Args:
        key_id: Key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    try:
        resp = client.cancel_key_deletion(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to cancel key deletion") from exc
    return CancelKeyDeletionResult(
        key_id=resp.get("KeyId"),
    )


def connect_custom_key_store(
    custom_key_store_id: str,
    region_name: str | None = None,
) -> None:
    """Connect custom key store.

    Args:
        custom_key_store_id: Custom key store id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["CustomKeyStoreId"] = custom_key_store_id
    try:
        client.connect_custom_key_store(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to connect custom key store") from exc
    return None


def create_alias(
    alias_name: str,
    target_key_id: str,
    region_name: str | None = None,
) -> None:
    """Create alias.

    Args:
        alias_name: Alias name.
        target_key_id: Target key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["AliasName"] = alias_name
    kwargs["TargetKeyId"] = target_key_id
    try:
        client.create_alias(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to create alias") from exc
    return None


def create_custom_key_store(
    custom_key_store_name: str,
    *,
    cloud_hsm_cluster_id: str | None = None,
    trust_anchor_certificate: str | None = None,
    key_store_password: str | None = None,
    custom_key_store_type: str | None = None,
    xks_proxy_uri_endpoint: str | None = None,
    xks_proxy_uri_path: str | None = None,
    xks_proxy_vpc_endpoint_service_name: str | None = None,
    xks_proxy_vpc_endpoint_service_owner: str | None = None,
    xks_proxy_authentication_credential: dict[str, Any] | None = None,
    xks_proxy_connectivity: str | None = None,
    region_name: str | None = None,
) -> CreateCustomKeyStoreResult:
    """Create custom key store.

    Args:
        custom_key_store_name: Custom key store name.
        cloud_hsm_cluster_id: Cloud hsm cluster id.
        trust_anchor_certificate: Trust anchor certificate.
        key_store_password: Key store password.
        custom_key_store_type: Custom key store type.
        xks_proxy_uri_endpoint: Xks proxy uri endpoint.
        xks_proxy_uri_path: Xks proxy uri path.
        xks_proxy_vpc_endpoint_service_name: Xks proxy vpc endpoint service name.
        xks_proxy_vpc_endpoint_service_owner: Xks proxy vpc endpoint service owner.
        xks_proxy_authentication_credential: Xks proxy authentication credential.
        xks_proxy_connectivity: Xks proxy connectivity.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["CustomKeyStoreName"] = custom_key_store_name
    if cloud_hsm_cluster_id is not None:
        kwargs["CloudHsmClusterId"] = cloud_hsm_cluster_id
    if trust_anchor_certificate is not None:
        kwargs["TrustAnchorCertificate"] = trust_anchor_certificate
    if key_store_password is not None:
        kwargs["KeyStorePassword"] = key_store_password
    if custom_key_store_type is not None:
        kwargs["CustomKeyStoreType"] = custom_key_store_type
    if xks_proxy_uri_endpoint is not None:
        kwargs["XksProxyUriEndpoint"] = xks_proxy_uri_endpoint
    if xks_proxy_uri_path is not None:
        kwargs["XksProxyUriPath"] = xks_proxy_uri_path
    if xks_proxy_vpc_endpoint_service_name is not None:
        kwargs["XksProxyVpcEndpointServiceName"] = xks_proxy_vpc_endpoint_service_name
    if xks_proxy_vpc_endpoint_service_owner is not None:
        kwargs["XksProxyVpcEndpointServiceOwner"] = xks_proxy_vpc_endpoint_service_owner
    if xks_proxy_authentication_credential is not None:
        kwargs["XksProxyAuthenticationCredential"] = xks_proxy_authentication_credential
    if xks_proxy_connectivity is not None:
        kwargs["XksProxyConnectivity"] = xks_proxy_connectivity
    try:
        resp = client.create_custom_key_store(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to create custom key store") from exc
    return CreateCustomKeyStoreResult(
        custom_key_store_id=resp.get("CustomKeyStoreId"),
    )


def create_grant(
    key_id: str,
    grantee_principal: str,
    operations: list[str],
    *,
    retiring_principal: str | None = None,
    constraints: dict[str, Any] | None = None,
    grant_tokens: list[str] | None = None,
    name: str | None = None,
    region_name: str | None = None,
) -> CreateGrantResult:
    """Create grant.

    Args:
        key_id: Key id.
        grantee_principal: Grantee principal.
        operations: Operations.
        retiring_principal: Retiring principal.
        constraints: Constraints.
        grant_tokens: Grant tokens.
        name: Name.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["GranteePrincipal"] = grantee_principal
    kwargs["Operations"] = operations
    if retiring_principal is not None:
        kwargs["RetiringPrincipal"] = retiring_principal
    if constraints is not None:
        kwargs["Constraints"] = constraints
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    if name is not None:
        kwargs["Name"] = name
    try:
        resp = client.create_grant(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to create grant") from exc
    return CreateGrantResult(
        grant_token=resp.get("GrantToken"),
        grant_id=resp.get("GrantId"),
    )


def create_key(
    *,
    policy: str | None = None,
    description: str | None = None,
    key_usage: str | None = None,
    customer_master_key_spec: str | None = None,
    key_spec: str | None = None,
    origin: str | None = None,
    custom_key_store_id: str | None = None,
    bypass_policy_lockout_safety_check: bool | None = None,
    tags: list[dict[str, Any]] | None = None,
    multi_region: bool | None = None,
    xks_key_id: str | None = None,
    region_name: str | None = None,
) -> CreateKeyResult:
    """Create key.

    Args:
        policy: Policy.
        description: Description.
        key_usage: Key usage.
        customer_master_key_spec: Customer master key spec.
        key_spec: Key spec.
        origin: Origin.
        custom_key_store_id: Custom key store id.
        bypass_policy_lockout_safety_check: Bypass policy lockout safety check.
        tags: Tags.
        multi_region: Multi region.
        xks_key_id: Xks key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    if policy is not None:
        kwargs["Policy"] = policy
    if description is not None:
        kwargs["Description"] = description
    if key_usage is not None:
        kwargs["KeyUsage"] = key_usage
    if customer_master_key_spec is not None:
        kwargs["CustomerMasterKeySpec"] = customer_master_key_spec
    if key_spec is not None:
        kwargs["KeySpec"] = key_spec
    if origin is not None:
        kwargs["Origin"] = origin
    if custom_key_store_id is not None:
        kwargs["CustomKeyStoreId"] = custom_key_store_id
    if bypass_policy_lockout_safety_check is not None:
        kwargs["BypassPolicyLockoutSafetyCheck"] = bypass_policy_lockout_safety_check
    if tags is not None:
        kwargs["Tags"] = tags
    if multi_region is not None:
        kwargs["MultiRegion"] = multi_region
    if xks_key_id is not None:
        kwargs["XksKeyId"] = xks_key_id
    try:
        resp = client.create_key(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to create key") from exc
    return CreateKeyResult(
        key_metadata=resp.get("KeyMetadata"),
    )


def delete_alias(
    alias_name: str,
    region_name: str | None = None,
) -> None:
    """Delete alias.

    Args:
        alias_name: Alias name.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["AliasName"] = alias_name
    try:
        client.delete_alias(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to delete alias") from exc
    return None


def delete_custom_key_store(
    custom_key_store_id: str,
    region_name: str | None = None,
) -> None:
    """Delete custom key store.

    Args:
        custom_key_store_id: Custom key store id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["CustomKeyStoreId"] = custom_key_store_id
    try:
        client.delete_custom_key_store(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to delete custom key store") from exc
    return None


def delete_imported_key_material(
    key_id: str,
    *,
    key_material_id: str | None = None,
    region_name: str | None = None,
) -> DeleteImportedKeyMaterialResult:
    """Delete imported key material.

    Args:
        key_id: Key id.
        key_material_id: Key material id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if key_material_id is not None:
        kwargs["KeyMaterialId"] = key_material_id
    try:
        resp = client.delete_imported_key_material(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to delete imported key material") from exc
    return DeleteImportedKeyMaterialResult(
        key_id=resp.get("KeyId"),
        key_material_id=resp.get("KeyMaterialId"),
    )


def derive_shared_secret(
    key_id: str,
    key_agreement_algorithm: str,
    public_key: bytes,
    *,
    grant_tokens: list[str] | None = None,
    recipient: dict[str, Any] | None = None,
    region_name: str | None = None,
) -> DeriveSharedSecretResult:
    """Derive shared secret.

    Args:
        key_id: Key id.
        key_agreement_algorithm: Key agreement algorithm.
        public_key: Public key.
        grant_tokens: Grant tokens.
        recipient: Recipient.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["KeyAgreementAlgorithm"] = key_agreement_algorithm
    kwargs["PublicKey"] = public_key
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    if recipient is not None:
        kwargs["Recipient"] = recipient
    try:
        resp = client.derive_shared_secret(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to derive shared secret") from exc
    return DeriveSharedSecretResult(
        key_id=resp.get("KeyId"),
        shared_secret=resp.get("SharedSecret"),
        ciphertext_for_recipient=resp.get("CiphertextForRecipient"),
        key_agreement_algorithm=resp.get("KeyAgreementAlgorithm"),
        key_origin=resp.get("KeyOrigin"),
    )


def describe_custom_key_stores(
    *,
    custom_key_store_id: str | None = None,
    custom_key_store_name: str | None = None,
    limit: int | None = None,
    marker: str | None = None,
    region_name: str | None = None,
) -> DescribeCustomKeyStoresResult:
    """Describe custom key stores.

    Args:
        custom_key_store_id: Custom key store id.
        custom_key_store_name: Custom key store name.
        limit: Limit.
        marker: Marker.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    if custom_key_store_id is not None:
        kwargs["CustomKeyStoreId"] = custom_key_store_id
    if custom_key_store_name is not None:
        kwargs["CustomKeyStoreName"] = custom_key_store_name
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    try:
        resp = client.describe_custom_key_stores(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to describe custom key stores") from exc
    return DescribeCustomKeyStoresResult(
        custom_key_stores=resp.get("CustomKeyStores"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def describe_key(
    key_id: str,
    *,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> DescribeKeyResult:
    """Describe key.

    Args:
        key_id: Key id.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.describe_key(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to describe key") from exc
    return DescribeKeyResult(
        key_metadata=resp.get("KeyMetadata"),
    )


def disable_key(
    key_id: str,
    region_name: str | None = None,
) -> None:
    """Disable key.

    Args:
        key_id: Key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    try:
        client.disable_key(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to disable key") from exc
    return None


def disable_key_rotation(
    key_id: str,
    region_name: str | None = None,
) -> None:
    """Disable key rotation.

    Args:
        key_id: Key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    try:
        client.disable_key_rotation(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to disable key rotation") from exc
    return None


def disconnect_custom_key_store(
    custom_key_store_id: str,
    region_name: str | None = None,
) -> None:
    """Disconnect custom key store.

    Args:
        custom_key_store_id: Custom key store id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["CustomKeyStoreId"] = custom_key_store_id
    try:
        client.disconnect_custom_key_store(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to disconnect custom key store") from exc
    return None


def enable_key(
    key_id: str,
    region_name: str | None = None,
) -> None:
    """Enable key.

    Args:
        key_id: Key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    try:
        client.enable_key(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to enable key") from exc
    return None


def enable_key_rotation(
    key_id: str,
    *,
    rotation_period_in_days: int | None = None,
    region_name: str | None = None,
) -> None:
    """Enable key rotation.

    Args:
        key_id: Key id.
        rotation_period_in_days: Rotation period in days.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if rotation_period_in_days is not None:
        kwargs["RotationPeriodInDays"] = rotation_period_in_days
    try:
        client.enable_key_rotation(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to enable key rotation") from exc
    return None


def generate_data_key_pair(
    key_id: str,
    key_pair_spec: str,
    *,
    encryption_context: dict[str, Any] | None = None,
    grant_tokens: list[str] | None = None,
    recipient: dict[str, Any] | None = None,
    region_name: str | None = None,
) -> GenerateDataKeyPairResult:
    """Generate data key pair.

    Args:
        key_id: Key id.
        key_pair_spec: Key pair spec.
        encryption_context: Encryption context.
        grant_tokens: Grant tokens.
        recipient: Recipient.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["KeyPairSpec"] = key_pair_spec
    if encryption_context is not None:
        kwargs["EncryptionContext"] = encryption_context
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    if recipient is not None:
        kwargs["Recipient"] = recipient
    try:
        resp = client.generate_data_key_pair(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to generate data key pair") from exc
    return GenerateDataKeyPairResult(
        private_key_ciphertext_blob=resp.get("PrivateKeyCiphertextBlob"),
        private_key_plaintext=resp.get("PrivateKeyPlaintext"),
        public_key=resp.get("PublicKey"),
        key_id=resp.get("KeyId"),
        key_pair_spec=resp.get("KeyPairSpec"),
        ciphertext_for_recipient=resp.get("CiphertextForRecipient"),
        key_material_id=resp.get("KeyMaterialId"),
    )


def generate_data_key_pair_without_plaintext(
    key_id: str,
    key_pair_spec: str,
    *,
    encryption_context: dict[str, Any] | None = None,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> GenerateDataKeyPairWithoutPlaintextResult:
    """Generate data key pair without plaintext.

    Args:
        key_id: Key id.
        key_pair_spec: Key pair spec.
        encryption_context: Encryption context.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["KeyPairSpec"] = key_pair_spec
    if encryption_context is not None:
        kwargs["EncryptionContext"] = encryption_context
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.generate_data_key_pair_without_plaintext(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to generate data key pair without plaintext") from exc
    return GenerateDataKeyPairWithoutPlaintextResult(
        private_key_ciphertext_blob=resp.get("PrivateKeyCiphertextBlob"),
        public_key=resp.get("PublicKey"),
        key_id=resp.get("KeyId"),
        key_pair_spec=resp.get("KeyPairSpec"),
        key_material_id=resp.get("KeyMaterialId"),
    )


def generate_data_key_without_plaintext(
    key_id: str,
    *,
    encryption_context: dict[str, Any] | None = None,
    key_spec: str | None = None,
    number_of_bytes: int | None = None,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> GenerateDataKeyWithoutPlaintextResult:
    """Generate data key without plaintext.

    Args:
        key_id: Key id.
        encryption_context: Encryption context.
        key_spec: Key spec.
        number_of_bytes: Number of bytes.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if encryption_context is not None:
        kwargs["EncryptionContext"] = encryption_context
    if key_spec is not None:
        kwargs["KeySpec"] = key_spec
    if number_of_bytes is not None:
        kwargs["NumberOfBytes"] = number_of_bytes
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.generate_data_key_without_plaintext(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to generate data key without plaintext") from exc
    return GenerateDataKeyWithoutPlaintextResult(
        ciphertext_blob=resp.get("CiphertextBlob"),
        key_id=resp.get("KeyId"),
        key_material_id=resp.get("KeyMaterialId"),
    )


def generate_mac(
    message: bytes,
    key_id: str,
    mac_algorithm: str,
    *,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> GenerateMacResult:
    """Generate mac.

    Args:
        message: Message.
        key_id: Key id.
        mac_algorithm: Mac algorithm.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["Message"] = message
    kwargs["KeyId"] = key_id
    kwargs["MacAlgorithm"] = mac_algorithm
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.generate_mac(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to generate mac") from exc
    return GenerateMacResult(
        mac=resp.get("Mac"),
        mac_algorithm=resp.get("MacAlgorithm"),
        key_id=resp.get("KeyId"),
    )


def generate_random(
    *,
    number_of_bytes: int | None = None,
    custom_key_store_id: str | None = None,
    recipient: dict[str, Any] | None = None,
    region_name: str | None = None,
) -> GenerateRandomResult:
    """Generate random.

    Args:
        number_of_bytes: Number of bytes.
        custom_key_store_id: Custom key store id.
        recipient: Recipient.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    if number_of_bytes is not None:
        kwargs["NumberOfBytes"] = number_of_bytes
    if custom_key_store_id is not None:
        kwargs["CustomKeyStoreId"] = custom_key_store_id
    if recipient is not None:
        kwargs["Recipient"] = recipient
    try:
        resp = client.generate_random(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to generate random") from exc
    return GenerateRandomResult(
        plaintext=resp.get("Plaintext"),
        ciphertext_for_recipient=resp.get("CiphertextForRecipient"),
    )


def get_key_policy(
    key_id: str,
    *,
    policy_name: str | None = None,
    region_name: str | None = None,
) -> GetKeyPolicyResult:
    """Get key policy.

    Args:
        key_id: Key id.
        policy_name: Policy name.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if policy_name is not None:
        kwargs["PolicyName"] = policy_name
    try:
        resp = client.get_key_policy(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to get key policy") from exc
    return GetKeyPolicyResult(
        policy=resp.get("Policy"),
        policy_name=resp.get("PolicyName"),
    )


def get_key_rotation_status(
    key_id: str,
    region_name: str | None = None,
) -> GetKeyRotationStatusResult:
    """Get key rotation status.

    Args:
        key_id: Key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    try:
        resp = client.get_key_rotation_status(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to get key rotation status") from exc
    return GetKeyRotationStatusResult(
        key_rotation_enabled=resp.get("KeyRotationEnabled"),
        key_id=resp.get("KeyId"),
        rotation_period_in_days=resp.get("RotationPeriodInDays"),
        next_rotation_date=resp.get("NextRotationDate"),
        on_demand_rotation_start_date=resp.get("OnDemandRotationStartDate"),
    )


def get_parameters_for_import(
    key_id: str,
    wrapping_algorithm: str,
    wrapping_key_spec: str,
    region_name: str | None = None,
) -> GetParametersForImportResult:
    """Get parameters for import.

    Args:
        key_id: Key id.
        wrapping_algorithm: Wrapping algorithm.
        wrapping_key_spec: Wrapping key spec.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["WrappingAlgorithm"] = wrapping_algorithm
    kwargs["WrappingKeySpec"] = wrapping_key_spec
    try:
        resp = client.get_parameters_for_import(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to get parameters for import") from exc
    return GetParametersForImportResult(
        key_id=resp.get("KeyId"),
        import_token=resp.get("ImportToken"),
        public_key=resp.get("PublicKey"),
        parameters_valid_to=resp.get("ParametersValidTo"),
    )


def get_public_key(
    key_id: str,
    *,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> GetPublicKeyResult:
    """Get public key.

    Args:
        key_id: Key id.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.get_public_key(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to get public key") from exc
    return GetPublicKeyResult(
        key_id=resp.get("KeyId"),
        public_key=resp.get("PublicKey"),
        customer_master_key_spec=resp.get("CustomerMasterKeySpec"),
        key_spec=resp.get("KeySpec"),
        key_usage=resp.get("KeyUsage"),
        encryption_algorithms=resp.get("EncryptionAlgorithms"),
        signing_algorithms=resp.get("SigningAlgorithms"),
        key_agreement_algorithms=resp.get("KeyAgreementAlgorithms"),
    )


def import_key_material(
    key_id: str,
    import_token: bytes,
    encrypted_key_material: bytes,
    *,
    valid_to: str | None = None,
    expiration_model: str | None = None,
    import_type: str | None = None,
    key_material_description: str | None = None,
    key_material_id: str | None = None,
    region_name: str | None = None,
) -> ImportKeyMaterialResult:
    """Import key material.

    Args:
        key_id: Key id.
        import_token: Import token.
        encrypted_key_material: Encrypted key material.
        valid_to: Valid to.
        expiration_model: Expiration model.
        import_type: Import type.
        key_material_description: Key material description.
        key_material_id: Key material id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["ImportToken"] = import_token
    kwargs["EncryptedKeyMaterial"] = encrypted_key_material
    if valid_to is not None:
        kwargs["ValidTo"] = valid_to
    if expiration_model is not None:
        kwargs["ExpirationModel"] = expiration_model
    if import_type is not None:
        kwargs["ImportType"] = import_type
    if key_material_description is not None:
        kwargs["KeyMaterialDescription"] = key_material_description
    if key_material_id is not None:
        kwargs["KeyMaterialId"] = key_material_id
    try:
        resp = client.import_key_material(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to import key material") from exc
    return ImportKeyMaterialResult(
        key_id=resp.get("KeyId"),
        key_material_id=resp.get("KeyMaterialId"),
    )


def list_aliases(
    *,
    key_id: str | None = None,
    limit: int | None = None,
    marker: str | None = None,
    region_name: str | None = None,
) -> ListAliasesResult:
    """List aliases.

    Args:
        key_id: Key id.
        limit: Limit.
        marker: Marker.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    if key_id is not None:
        kwargs["KeyId"] = key_id
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    try:
        resp = client.list_aliases(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to list aliases") from exc
    return ListAliasesResult(
        aliases=resp.get("Aliases"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def list_grants(
    key_id: str,
    *,
    limit: int | None = None,
    marker: str | None = None,
    grant_id: str | None = None,
    grantee_principal: str | None = None,
    region_name: str | None = None,
) -> ListGrantsResult:
    """List grants.

    Args:
        key_id: Key id.
        limit: Limit.
        marker: Marker.
        grant_id: Grant id.
        grantee_principal: Grantee principal.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    if grant_id is not None:
        kwargs["GrantId"] = grant_id
    if grantee_principal is not None:
        kwargs["GranteePrincipal"] = grantee_principal
    try:
        resp = client.list_grants(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to list grants") from exc
    return ListGrantsResult(
        grants=resp.get("Grants"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def list_key_policies(
    key_id: str,
    *,
    limit: int | None = None,
    marker: str | None = None,
    region_name: str | None = None,
) -> ListKeyPoliciesResult:
    """List key policies.

    Args:
        key_id: Key id.
        limit: Limit.
        marker: Marker.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    try:
        resp = client.list_key_policies(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to list key policies") from exc
    return ListKeyPoliciesResult(
        policy_names=resp.get("PolicyNames"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def list_key_rotations(
    key_id: str,
    *,
    include_key_material: str | None = None,
    limit: int | None = None,
    marker: str | None = None,
    region_name: str | None = None,
) -> ListKeyRotationsResult:
    """List key rotations.

    Args:
        key_id: Key id.
        include_key_material: Include key material.
        limit: Limit.
        marker: Marker.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if include_key_material is not None:
        kwargs["IncludeKeyMaterial"] = include_key_material
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    try:
        resp = client.list_key_rotations(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to list key rotations") from exc
    return ListKeyRotationsResult(
        rotations=resp.get("Rotations"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def list_keys(
    *,
    limit: int | None = None,
    marker: str | None = None,
    region_name: str | None = None,
) -> ListKeysResult:
    """List keys.

    Args:
        limit: Limit.
        marker: Marker.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    try:
        resp = client.list_keys(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to list keys") from exc
    return ListKeysResult(
        keys=resp.get("Keys"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def list_resource_tags(
    key_id: str,
    *,
    limit: int | None = None,
    marker: str | None = None,
    region_name: str | None = None,
) -> ListResourceTagsResult:
    """List resource tags.

    Args:
        key_id: Key id.
        limit: Limit.
        marker: Marker.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    try:
        resp = client.list_resource_tags(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to list resource tags") from exc
    return ListResourceTagsResult(
        tags=resp.get("Tags"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def list_retirable_grants(
    retiring_principal: str,
    *,
    limit: int | None = None,
    marker: str | None = None,
    region_name: str | None = None,
) -> ListRetirableGrantsResult:
    """List retirable grants.

    Args:
        retiring_principal: Retiring principal.
        limit: Limit.
        marker: Marker.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["RetiringPrincipal"] = retiring_principal
    if limit is not None:
        kwargs["Limit"] = limit
    if marker is not None:
        kwargs["Marker"] = marker
    try:
        resp = client.list_retirable_grants(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to list retirable grants") from exc
    return ListRetirableGrantsResult(
        grants=resp.get("Grants"),
        next_marker=resp.get("NextMarker"),
        truncated=resp.get("Truncated"),
    )


def put_key_policy(
    key_id: str,
    policy: str,
    *,
    policy_name: str | None = None,
    bypass_policy_lockout_safety_check: bool | None = None,
    region_name: str | None = None,
) -> None:
    """Put key policy.

    Args:
        key_id: Key id.
        policy: Policy.
        policy_name: Policy name.
        bypass_policy_lockout_safety_check: Bypass policy lockout safety check.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["Policy"] = policy
    if policy_name is not None:
        kwargs["PolicyName"] = policy_name
    if bypass_policy_lockout_safety_check is not None:
        kwargs["BypassPolicyLockoutSafetyCheck"] = bypass_policy_lockout_safety_check
    try:
        client.put_key_policy(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to put key policy") from exc
    return None


def replicate_key(
    key_id: str,
    replica_region: str,
    *,
    policy: str | None = None,
    bypass_policy_lockout_safety_check: bool | None = None,
    description: str | None = None,
    tags: list[dict[str, Any]] | None = None,
    region_name: str | None = None,
) -> ReplicateKeyResult:
    """Replicate key.

    Args:
        key_id: Key id.
        replica_region: Replica region.
        policy: Policy.
        bypass_policy_lockout_safety_check: Bypass policy lockout safety check.
        description: Description.
        tags: Tags.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["ReplicaRegion"] = replica_region
    if policy is not None:
        kwargs["Policy"] = policy
    if bypass_policy_lockout_safety_check is not None:
        kwargs["BypassPolicyLockoutSafetyCheck"] = bypass_policy_lockout_safety_check
    if description is not None:
        kwargs["Description"] = description
    if tags is not None:
        kwargs["Tags"] = tags
    try:
        resp = client.replicate_key(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to replicate key") from exc
    return ReplicateKeyResult(
        replica_key_metadata=resp.get("ReplicaKeyMetadata"),
        replica_policy=resp.get("ReplicaPolicy"),
        replica_tags=resp.get("ReplicaTags"),
    )


def retire_grant(
    *,
    grant_token: str | None = None,
    key_id: str | None = None,
    grant_id: str | None = None,
    region_name: str | None = None,
) -> None:
    """Retire grant.

    Args:
        grant_token: Grant token.
        key_id: Key id.
        grant_id: Grant id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    if grant_token is not None:
        kwargs["GrantToken"] = grant_token
    if key_id is not None:
        kwargs["KeyId"] = key_id
    if grant_id is not None:
        kwargs["GrantId"] = grant_id
    try:
        client.retire_grant(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to retire grant") from exc
    return None


def revoke_grant(
    key_id: str,
    grant_id: str,
    region_name: str | None = None,
) -> None:
    """Revoke grant.

    Args:
        key_id: Key id.
        grant_id: Grant id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["GrantId"] = grant_id
    try:
        client.revoke_grant(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to revoke grant") from exc
    return None


def rotate_key_on_demand(
    key_id: str,
    region_name: str | None = None,
) -> RotateKeyOnDemandResult:
    """Rotate key on demand.

    Args:
        key_id: Key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    try:
        resp = client.rotate_key_on_demand(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to rotate key on demand") from exc
    return RotateKeyOnDemandResult(
        key_id=resp.get("KeyId"),
    )


def schedule_key_deletion(
    key_id: str,
    *,
    pending_window_in_days: int | None = None,
    region_name: str | None = None,
) -> ScheduleKeyDeletionResult:
    """Schedule key deletion.

    Args:
        key_id: Key id.
        pending_window_in_days: Pending window in days.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    if pending_window_in_days is not None:
        kwargs["PendingWindowInDays"] = pending_window_in_days
    try:
        resp = client.schedule_key_deletion(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to schedule key deletion") from exc
    return ScheduleKeyDeletionResult(
        key_id=resp.get("KeyId"),
        deletion_date=resp.get("DeletionDate"),
        key_state=resp.get("KeyState"),
        pending_window_in_days=resp.get("PendingWindowInDays"),
    )


def sign(
    key_id: str,
    message: bytes,
    signing_algorithm: str,
    *,
    message_type: str | None = None,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> SignResult:
    """Sign.

    Args:
        key_id: Key id.
        message: Message.
        signing_algorithm: Signing algorithm.
        message_type: Message type.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["Message"] = message
    kwargs["SigningAlgorithm"] = signing_algorithm
    if message_type is not None:
        kwargs["MessageType"] = message_type
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.sign(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to sign") from exc
    return SignResult(
        key_id=resp.get("KeyId"),
        signature=resp.get("Signature"),
        signing_algorithm=resp.get("SigningAlgorithm"),
    )


def tag_resource(
    key_id: str,
    tags: list[dict[str, Any]],
    region_name: str | None = None,
) -> None:
    """Tag resource.

    Args:
        key_id: Key id.
        tags: Tags.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["Tags"] = tags
    try:
        client.tag_resource(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to tag resource") from exc
    return None


def untag_resource(
    key_id: str,
    tag_keys: list[str],
    region_name: str | None = None,
) -> None:
    """Untag resource.

    Args:
        key_id: Key id.
        tag_keys: Tag keys.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["TagKeys"] = tag_keys
    try:
        client.untag_resource(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to untag resource") from exc
    return None


def update_alias(
    alias_name: str,
    target_key_id: str,
    region_name: str | None = None,
) -> None:
    """Update alias.

    Args:
        alias_name: Alias name.
        target_key_id: Target key id.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["AliasName"] = alias_name
    kwargs["TargetKeyId"] = target_key_id
    try:
        client.update_alias(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to update alias") from exc
    return None


def update_custom_key_store(
    custom_key_store_id: str,
    *,
    new_custom_key_store_name: str | None = None,
    key_store_password: str | None = None,
    cloud_hsm_cluster_id: str | None = None,
    xks_proxy_uri_endpoint: str | None = None,
    xks_proxy_uri_path: str | None = None,
    xks_proxy_vpc_endpoint_service_name: str | None = None,
    xks_proxy_vpc_endpoint_service_owner: str | None = None,
    xks_proxy_authentication_credential: dict[str, Any] | None = None,
    xks_proxy_connectivity: str | None = None,
    region_name: str | None = None,
) -> None:
    """Update custom key store.

    Args:
        custom_key_store_id: Custom key store id.
        new_custom_key_store_name: New custom key store name.
        key_store_password: Key store password.
        cloud_hsm_cluster_id: Cloud hsm cluster id.
        xks_proxy_uri_endpoint: Xks proxy uri endpoint.
        xks_proxy_uri_path: Xks proxy uri path.
        xks_proxy_vpc_endpoint_service_name: Xks proxy vpc endpoint service name.
        xks_proxy_vpc_endpoint_service_owner: Xks proxy vpc endpoint service owner.
        xks_proxy_authentication_credential: Xks proxy authentication credential.
        xks_proxy_connectivity: Xks proxy connectivity.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["CustomKeyStoreId"] = custom_key_store_id
    if new_custom_key_store_name is not None:
        kwargs["NewCustomKeyStoreName"] = new_custom_key_store_name
    if key_store_password is not None:
        kwargs["KeyStorePassword"] = key_store_password
    if cloud_hsm_cluster_id is not None:
        kwargs["CloudHsmClusterId"] = cloud_hsm_cluster_id
    if xks_proxy_uri_endpoint is not None:
        kwargs["XksProxyUriEndpoint"] = xks_proxy_uri_endpoint
    if xks_proxy_uri_path is not None:
        kwargs["XksProxyUriPath"] = xks_proxy_uri_path
    if xks_proxy_vpc_endpoint_service_name is not None:
        kwargs["XksProxyVpcEndpointServiceName"] = xks_proxy_vpc_endpoint_service_name
    if xks_proxy_vpc_endpoint_service_owner is not None:
        kwargs["XksProxyVpcEndpointServiceOwner"] = xks_proxy_vpc_endpoint_service_owner
    if xks_proxy_authentication_credential is not None:
        kwargs["XksProxyAuthenticationCredential"] = xks_proxy_authentication_credential
    if xks_proxy_connectivity is not None:
        kwargs["XksProxyConnectivity"] = xks_proxy_connectivity
    try:
        client.update_custom_key_store(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to update custom key store") from exc
    return None


def update_key_description(
    key_id: str,
    description: str,
    region_name: str | None = None,
) -> None:
    """Update key description.

    Args:
        key_id: Key id.
        description: Description.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["Description"] = description
    try:
        client.update_key_description(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to update key description") from exc
    return None


def update_primary_region(
    key_id: str,
    primary_region: str,
    region_name: str | None = None,
) -> None:
    """Update primary region.

    Args:
        key_id: Key id.
        primary_region: Primary region.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["PrimaryRegion"] = primary_region
    try:
        client.update_primary_region(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to update primary region") from exc
    return None


def verify(
    key_id: str,
    message: bytes,
    signature: bytes,
    signing_algorithm: str,
    *,
    message_type: str | None = None,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> VerifyResult:
    """Verify.

    Args:
        key_id: Key id.
        message: Message.
        signature: Signature.
        signing_algorithm: Signing algorithm.
        message_type: Message type.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["KeyId"] = key_id
    kwargs["Message"] = message
    kwargs["Signature"] = signature
    kwargs["SigningAlgorithm"] = signing_algorithm
    if message_type is not None:
        kwargs["MessageType"] = message_type
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.verify(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to verify") from exc
    return VerifyResult(
        key_id=resp.get("KeyId"),
        signature_valid=resp.get("SignatureValid"),
        signing_algorithm=resp.get("SigningAlgorithm"),
    )


def verify_mac(
    message: bytes,
    key_id: str,
    mac_algorithm: str,
    mac: bytes,
    *,
    grant_tokens: list[str] | None = None,
    region_name: str | None = None,
) -> VerifyMacResult:
    """Verify mac.

    Args:
        message: Message.
        key_id: Key id.
        mac_algorithm: Mac algorithm.
        mac: Mac.
        grant_tokens: Grant tokens.
        region_name: AWS region override.

    Raises:
        RuntimeError: If the API call fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict[str, Any] = {}
    kwargs["Message"] = message
    kwargs["KeyId"] = key_id
    kwargs["MacAlgorithm"] = mac_algorithm
    kwargs["Mac"] = mac
    if grant_tokens is not None:
        kwargs["GrantTokens"] = grant_tokens
    try:
        resp = client.verify_mac(**kwargs)
    except ClientError as exc:
        raise wrap_aws_error(exc, "Failed to verify mac") from exc
    return VerifyMacResult(
        key_id=resp.get("KeyId"),
        mac_valid=resp.get("MacValid"),
        mac_algorithm=resp.get("MacAlgorithm"),
    )
