"""Tests for aws_util.aio.credential_rotation — 100% line coverage."""
from __future__ import annotations

import json
from typing import Any
from unittest.mock import AsyncMock

import pytest

from aws_util.aio import credential_rotation as mod
from aws_util.credential_rotation import (
    CredentialRotationResult,
    _generate_password,
)



REGION = "us-east-1"
# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_mock_client(**overrides: Any) -> AsyncMock:
    """Return an AsyncMock that behaves like an AsyncClient."""
    client = AsyncMock()
    client.call = AsyncMock(**overrides)
    return client


# ---------------------------------------------------------------------------
# Full rotation — happy path
# ---------------------------------------------------------------------------


class TestDatabaseCredentialRotatorFull:
    async def test_full_rotation_success(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Full five-step rotation with SNS, signal table, and history."""
        current_secret = json.dumps(
            {"username": "admin", "password": "old_pass"}
        )
        pending_secret = json.dumps(
            {"username": "admin", "password": "new_pass"}
        )

        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                # Step 1: GetSecretValue (current)
                {"SecretString": current_secret},
                # Step 1: PutSecretValue
                {"VersionId": "v-new-123"},
                # Step 2: GetSecretValue (pending)
                {"SecretString": pending_secret},
                # Step 5: DescribeSecret
                {
                    "VersionIdsToStages": {
                        "v-old-111": ["AWSCURRENT"],
                        "v-new-123": ["AWSPENDING"],
                    }
                },
                # Step 5: UpdateSecretVersionStage
                {},
            ]
        )

        sns = AsyncMock()
        sns.call = AsyncMock(return_value={})

        ddb = AsyncMock()
        ddb.call = AsyncMock(return_value={})

        clients: dict[str, AsyncMock] = {
            "secretsmanager": sm,
            "sns": sns,
            "dynamodb": ddb,
        }
        monkeypatch.setattr(
            mod,
            "async_client",
            lambda svc, rn=None: clients.get(svc, AsyncMock()),
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        result = await mod.database_credential_rotator(
            secret_name="myapp/db",
            new_password="new_pass",
            consumer_sns_topic_arn="arn:aws:sns:us-east-1:123:topic",
            signal_table_name="rotation-signals",
            history_table_name="rotation-history",
            drain_seconds=10,
            region_name=REGION,
        )

        assert result.secret_name == "myapp/db"
        assert result.new_version_id == "v-new-123"
        assert result.validation_passed is True
        assert result.consumers_notified == 2
        assert result.drain_seconds == 10
        assert result.finalized is True
        assert result.rotation_timestamp

        # SNS was called
        sns.call.assert_awaited_once()
        # DynamoDB was called twice (signal + history)
        assert ddb.call.await_count == 2


# ---------------------------------------------------------------------------
# Auto-generated password
# ---------------------------------------------------------------------------


class TestAutoGeneratedPassword:
    async def test_auto_generated_password(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Password auto-generated when new_password is None."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": json.dumps({"username": "admin"})},
                {"VersionId": "v-auto"},
                {
                    "SecretString": json.dumps(
                        {"username": "admin", "password": "auto"}
                    )
                },
                {
                    "VersionIdsToStages": {
                        "v-old": ["AWSCURRENT"],
                        "v-auto": ["AWSPENDING"],
                    }
                },
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        result = await mod.database_credential_rotator(
            secret_name="myapp/db",
            new_password=None,
            drain_seconds=0,
        )

        assert result.new_version_id == "v-auto"
        assert result.finalized is True
        # Check the PutSecretValue call (second call)
        put_call = sm.call.call_args_list[1]
        secret_data = json.loads(put_call.kwargs["SecretString"])
        assert "password" in secret_data
        assert len(secret_data["password"]) == 40


# ---------------------------------------------------------------------------
# No optional services
# ---------------------------------------------------------------------------


class TestNoOptionalServices:
    async def test_no_optional_services(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Rotation without SNS, signal table, or history table."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v0": ["AWSCURRENT"],
                        "v1": ["AWSPENDING"],
                    }
                },
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        result = await mod.database_credential_rotator(
            secret_name="s",
            new_password="pw",
            drain_seconds=0,
        )

        assert result.consumers_notified == 0
        assert result.finalized is True


# ---------------------------------------------------------------------------
# Step 1 error paths
# ---------------------------------------------------------------------------


class TestStep1Errors:
    async def test_get_current_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=RuntimeError("not found")
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        with pytest.raises(
            RuntimeError, match="Failed to retrieve current secret"
        ):
            await mod.database_credential_rotator(
                secret_name="missing", new_password="pw"
            )

    async def test_put_pending_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                RuntimeError("internal"),
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        with pytest.raises(
            RuntimeError, match="Failed to put AWSPENDING"
        ):
            await mod.database_credential_rotator(
                secret_name="s", new_password="pw"
            )


# ---------------------------------------------------------------------------
# Step 2 error paths
# ---------------------------------------------------------------------------


class TestStep2Errors:
    async def test_validation_get_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                RuntimeError("not found"),
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        with pytest.raises(
            RuntimeError, match="Failed to validate AWSPENDING"
        ):
            await mod.database_credential_rotator(
                secret_name="s", new_password="pw"
            )

    async def test_validation_bad_json(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": "not-json"},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        with pytest.raises(
            RuntimeError, match="Validation failed"
        ):
            await mod.database_credential_rotator(
                secret_name="s", new_password="pw"
            )

    async def test_validation_no_password_key(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {
                    "SecretString": json.dumps(
                        {"username": "admin"}
                    )
                },
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        with pytest.raises(
            RuntimeError, match="'password' key missing"
        ):
            await mod.database_credential_rotator(
                secret_name="s", new_password="pw"
            )


# ---------------------------------------------------------------------------
# Step 3 error paths
# ---------------------------------------------------------------------------


class TestStep3Errors:
    async def test_sns_publish_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
            ]
        )

        sns = AsyncMock()
        sns.call = AsyncMock(
            side_effect=RuntimeError("invalid param")
        )

        clients = {"secretsmanager": sm, "sns": sns}
        monkeypatch.setattr(
            mod,
            "async_client",
            lambda svc, rn=None: clients.get(svc, AsyncMock()),
        )

        with pytest.raises(
            RuntimeError, match="Failed to publish rotation"
        ):
            await mod.database_credential_rotator(
                secret_name="s",
                new_password="pw",
                consumer_sns_topic_arn="arn:aws:sns:us-east-1:123:t",
            )

    async def test_signal_table_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
            ]
        )

        ddb = AsyncMock()
        ddb.call = AsyncMock(
            side_effect=RuntimeError("table not found")
        )

        clients = {"secretsmanager": sm, "dynamodb": ddb}
        monkeypatch.setattr(
            mod,
            "async_client",
            lambda svc, rn=None: clients.get(svc, AsyncMock()),
        )

        with pytest.raises(
            RuntimeError, match="Failed to write rotation signal"
        ):
            await mod.database_credential_rotator(
                secret_name="s",
                new_password="pw",
                signal_table_name="bad-table",
            )


# ---------------------------------------------------------------------------
# Step 4 drain
# ---------------------------------------------------------------------------


class TestStep4Drain:
    async def test_drain_increments(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Verify drain uses incremental sleeps."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v0": ["AWSCURRENT"],
                        "v1": ["AWSPENDING"],
                    }
                },
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        sleep_calls: list[float] = []

        async def mock_sleep(s: float) -> None:
            sleep_calls.append(s)

        monkeypatch.setattr(mod.asyncio, "sleep", mock_sleep)

        await mod.database_credential_rotator(
            secret_name="s",
            new_password="pw",
            drain_seconds=12,
        )

        # 12 seconds = 5 + 5 + 2
        assert sleep_calls == [5, 5, 2]

    async def test_drain_zero_seconds(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Drain with 0 seconds does not sleep."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v0": ["AWSCURRENT"],
                        "v1": ["AWSPENDING"],
                    }
                },
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        sleep_calls: list[float] = []

        async def mock_sleep(s: float) -> None:
            sleep_calls.append(s)

        monkeypatch.setattr(mod.asyncio, "sleep", mock_sleep)

        await mod.database_credential_rotator(
            secret_name="s",
            new_password="pw",
            drain_seconds=0,
        )

        assert sleep_calls == []


# ---------------------------------------------------------------------------
# Step 5 error paths
# ---------------------------------------------------------------------------


class TestStep5Errors:
    async def test_describe_secret_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                RuntimeError("internal"),
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        with pytest.raises(
            RuntimeError, match="Failed to describe secret"
        ):
            await mod.database_credential_rotator(
                secret_name="s",
                new_password="pw",
                drain_seconds=0,
            )

    async def test_finalize_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v0": ["AWSCURRENT"],
                        "v1": ["AWSPENDING"],
                    }
                },
                RuntimeError("internal"),
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        with pytest.raises(
            RuntimeError, match="Failed to finalize rotation"
        ):
            await mod.database_credential_rotator(
                secret_name="s",
                new_password="pw",
                drain_seconds=0,
            )

    async def test_history_table_fails(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v0": ["AWSCURRENT"],
                        "v1": ["AWSPENDING"],
                    }
                },
                {},  # UpdateSecretVersionStage succeeds
            ]
        )

        ddb = AsyncMock()
        ddb.call = AsyncMock(
            side_effect=RuntimeError("table not found")
        )

        clients = {"secretsmanager": sm, "dynamodb": ddb}
        monkeypatch.setattr(
            mod,
            "async_client",
            lambda svc, rn=None: clients.get(svc, AsyncMock()),
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        with pytest.raises(
            RuntimeError, match="Failed to record rotation history"
        ):
            await mod.database_credential_rotator(
                secret_name="s",
                new_password="pw",
                drain_seconds=0,
                history_table_name="bad-table",
            )


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    async def test_no_previous_current_version(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Finalize when no other version has AWSCURRENT."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {"VersionIdsToStages": {"v1": ["AWSPENDING"]}},
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        result = await mod.database_credential_rotator(
            secret_name="s",
            new_password="pw",
            drain_seconds=0,
        )

        assert result.finalized is True
        # Check UpdateSecretVersionStage call (5th call)
        update_call = sm.call.call_args_list[4]
        assert "RemoveFromVersionId" not in update_call.kwargs

    async def test_current_secret_not_json(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Current secret is not valid JSON; password still set."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "plain-text-secret"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v0": ["AWSCURRENT"],
                        "v1": ["AWSPENDING"],
                    }
                },
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        result = await mod.database_credential_rotator(
            secret_name="s",
            new_password="pw",
            drain_seconds=0,
        )

        assert result.finalized is True
        # Check PutSecretValue call (2nd call)
        put_call = sm.call.call_args_list[1]
        secret_data = json.loads(put_call.kwargs["SecretString"])
        assert secret_data == {"password": "pw"}

    async def test_new_version_already_current(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Edge case: new version is already the current version."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v1": ["AWSCURRENT", "AWSPENDING"],
                    }
                },
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        result = await mod.database_credential_rotator(
            secret_name="s",
            new_password="pw",
            drain_seconds=0,
        )

        assert result.finalized is True
        update_call = sm.call.call_args_list[4]
        assert "RemoveFromVersionId" not in update_call.kwargs

    async def test_current_secret_missing_secret_string(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Current secret response has no SecretString key."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {},  # No SecretString key
                {"VersionId": "v1"},
                {"SecretString": json.dumps({"password": "pw"})},
                {
                    "VersionIdsToStages": {
                        "v0": ["AWSCURRENT"],
                        "v1": ["AWSPENDING"],
                    }
                },
                {},
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )
        monkeypatch.setattr(mod.asyncio, "sleep", AsyncMock())

        result = await mod.database_credential_rotator(
            secret_name="s",
            new_password="pw",
            drain_seconds=0,
        )

        assert result.finalized is True

    async def test_pending_secret_empty_string(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Pending secret returns empty SecretString."""
        sm = AsyncMock()
        sm.call = AsyncMock(
            side_effect=[
                {"SecretString": "{}"},
                {"VersionId": "v1"},
                {"SecretString": ""},  # empty
            ]
        )

        monkeypatch.setattr(
            mod, "async_client", lambda svc, rn=None: sm
        )

        with pytest.raises(
            RuntimeError, match="Validation failed"
        ):
            await mod.database_credential_rotator(
                secret_name="s", new_password="pw"
            )
